version: "3.3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'productos'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sonic'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
    - '3306:3306'
    expose:
    - '3306'
    volumes:
      - ./data:/data/db
    networks:
      - backend
  node:
    build:
      context: .
    restart: always
    links:
      - mysql:mysql
    ports:
      - "8080:3000"
    environment:
      DB_HOSTNAME: 'mysql'
    networks:
      - backend
networks:
    backend:
